[project]
name = "george-blog"
version = "0.1.0"
description = "A blog sample written in Python with Flask"
requires-python = ">=3.12, <3.13"
dependencies = [
    "python-decouple",
    "Flask",
    "Flask-Bootstrap",
    "Flask-CKEditor",
    "Werkzeug",
    "Flask-SQLAlchemy",
    "SQLAlchemy",
    "Flask-Login",
    "Flask-WTF",
    "WTForms",
    "psycopg2-binary",
    "gunicorn",
]
