"""Add is_admin role

Revision ID: 696bbb6e53c6
Revises: f0bc44acda68
Create Date: 2026-10-03 14:09:08.797919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696bbb6e53c6'
down_revision = 'f0bc44acda68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###

    op.execute(
        'UPDATE "user" SET is_admin = true WHERE id = 1'
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
